apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: iamroles.iam.amazonaws.com
spec:
  group: iam.amazonaws.com
  names:
    kind: IamRole
    plural: iamroles
    shortNames:
    - ir
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        definition:
          properties:
            providerID:
              description: ExternalId is a unique identifier that might be required
                when you assume a role in another account
              type: string
            roleARN:
              description: RoleArn is the Amazon Resource Name (ARN) of the role to
                assume.
              type: string
          required:
          - roleARN
          type: object
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
